service: LeodanLetsGoServerless
provider:
  name: aws
  region: us-east-1
  role: arn:aws:iam::859647202319:role/LetsGoServerlessLambdaExecution
  runtime: python3.8
  timeout: 360
functions:
  LeodanSuma:
    name: LeodanSuma
    handler: lambda_handler.suma
    environment:
      PASSWORD: password_lambda
    maximumRetryAttempts: 0
    description: Function that takes two operands and returns the sum of the two operands
package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'